"use client"
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { NextUIProviders } from "./providers/providers";
import { AuthContextProvider } from "./context/AuthContext";
import { Provider } from 'react-redux';
import store from './redux/store';
import "react-toastify/dist/ReactToastify.css";


const inter = Montserrat({ subsets: ['latin'] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />

        <link href="/favicon.ico" rel="icon" />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
          <AuthContextProvider>
            <NextUIProviders>
              {children}
            </NextUIProviders>
          </AuthContextProvider>
        </Provider>
      </body>
    </html>
  );
}
