// *ACCOUNTS
export const GET_CURRENT_ACCOUNT_REQUESTED = "GET_CURRENT_ACCOUNT_REQUESTED";
export const GET_CURRENT_ACCOUNT_SUCCESS = "GET_CURRENT_ACCOUNT_SUCCESS";
export const GET_CURRENT_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";

export const GET_ACCOUNTS_REQUESTED = "GET_ACCOUNTS_REQUESTED";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAILED = "GET_ACCOUNTS_FAILED";

export const CREATE_ACCOUNT_REQUESTED = "CREATE_ACCOUNT_REQUESTED";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";

// *BOOKS
export const GET_BOOKS_REQUESTED = "GET_BOOKS_REQUESTED";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const GET_BOOK_REQUESTED = "GET_BOOK_REQUESTED";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILED = "GET_BOOK_FAILED";

export const SEARCH_BOOKS_REQUESTED = "SEARCH_BOOKS_REQUESTED";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAILED = "SEARCH_BOOKS_FAILED";

export const INCREASE_TOTAL_READ_REQUESTED = "INCREASE_TOTAL_READ_REQUESTED";
export const INCREASE_TOTAL_READ_SUCCESS = "INCREASE_TOTAL_READ_SUCCESS";
export const INCREASE_TOTAL_READ_FAIL = "INCREASE_TOTAL_READ_FAIL";

export const INCREASE_TOTAL_SAVED_REQUESTED = "INCREASE_TOTAL_SAVED_REQUESTED";
export const INCREASE_TOTAL_SAVED_SUCCESS = "INCREASE_TOTAL_SAVED_SUCCESS";
export const INCREASE_TOTAL_SAVED_FAIL = "INCREASE_TOTAL_SAVED_FAIL";

// *MEMBERSHIP
export const REGISTER_MEMBERSHIP_REQUESTED = "REGISTER_MEMBERSHIP_REQUESTED";
export const REGISTER_MEMBERSHIP_SUCCESS = "REGISTER_MEMBERSHIP_SUCCESS";
export const REGISTER_MEMBERSHIP_FAILED = "REGISTER_MEMBERSHIP_FAILED";
