name: CI - Frontend
on:
  pull_request:
    paths:
      - "**/*"
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u nguyenlien -p C!gtnH7yWyM24uX
      - name: Build frontend
        run: docker build -t nguyenlien/mori-frontend .
      - name: Push image
        run: docker push nguyenlien/mori-frontend
