image: docker:20.10.14

services:
  - docker:20.10.14-dind

variables:
  DOCKER_IMAGE: "qhuong1008/mori-frontend"
  DOCKER_USER: "qhuong1008"
  DOCKER_PASSWORD: "Huong560045@"
  REMOTE_SERVER: "hcmute@103.130.211.150"
  REMOTE_PORT: 10038

stages:
  - build
  - deploy

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

build:
  stage: build
  script:
    - docker build -t frontend .
    - docker tag frontend "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

deploy:
  stage: deploy
  environment: production
  script:
    - ssh hcmute@103.130.211.150 -p 10038
    - hcmute@fit
    - cd project/MoriApp_20110141_20110335/mori-app-deploy
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d

  only:
    - main
